kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.cacheService.name }}-secret
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.dg.car.cacheName: {{ .Values.kafka2datagrid.datagrid.cache.car }}
    com.redhat.bobbycar.camelk.dg.zone.cacheName: {{ .Values.kafka2datagrid.datagrid.cache.zone }}
    com.redhat.bobbycar.camelk.dg.host: {{ .Values.kafka2datagrid.datagrid.account.host }}
    com.redhat.bobbycar.camelk.dg.password: {{ .Values.kafka2datagrid.datagrid.account.password }}
    com.redhat.bobbycar.camelk.dg.user: {{ .Values.kafka2datagrid.datagrid.account.user }}
type: Opaque