kind: Secret
apiVersion: v1
metadata:
  name: cache-service-secret
stringData:
  application.properties: |-
    com.redhat.rover.camelk.dg.car.cacheName: {{ .Values.datagrid.cache.car }}
    com.redhat.rover.camelk.dg.zone.cacheName: {{ .Values.datagrid.cache.zone }}
    com.redhat.rover.camelk.dg.host: rover-dg
    com.redhat.rover.camelk.dg.password: {{ .Values.datagrid.account.password }}
    com.redhat.rover.camelk.dg.user: {{ .Values.datagrid.account.user }}
type: Opaque