kind: Secret
apiVersion: v1
metadata:
  name: kafka2datagrid-secret
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.dg.car.snapshot.cacheName: {{ .Values.kafka2datagrid.datagrid.cache.snapshot }}
    com.redhat.bobbycar.camelk.dg.car.cacheName: {{ .Values.kafka2datagrid.datagrid.cache.car }}
    com.redhat.bobbycar.camelk.dg.zone.cacheName: {{ .Values.kafka2datagrid.datagrid.cache.zone }}
    com.redhat.bobbycar.camelk.dg.host: {{ .Values.kafka2datagrid.datagrid.account.host }}
    com.redhat.bobbycar.camelk.dg.password: {{ .Values.kafka2datagrid.datagrid.account.password }}
    com.redhat.bobbycar.camelk.dg.user: {{ .Values.kafka2datagrid.datagrid.account.user }}
    com.redhat.bobbycar.camelk.kafka.brokers: {{ .Values.kafka2datagrid.kafka.host }}
    com.redhat.bobbycar.camelk.kafka.topic: {{ .Values.kafka2datagrid.kafka.topic }}
    com.redhat.bobbycar.camelk.mqtt.brokerUrl: {{ .Values.kafka2datagrid.mqtt.host }}
    com.redhat.bobbycar.camelk.mqtt.topic: {{ .Values.kafka2datagrid.mqtt.topic }}
    com.redhat.bobbycar.camelk.dg.ocp.api: {{ .Values.kafka2datagrid.ocp.api }}
    com.redhat.bobbycar.camelk.dg.namespace: {{ .Values.namespace }}
type: Opaque

    
