kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.mqtt2kafka.name }}-secret
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.kafka.brokers: {{ .Values.mqtt2kafka.kafka.host }}
    com.redhat.bobbycar.camelk.kafka.topic: {{ .Values.mqtt2kafka.kafka.topic }}
    com.redhat.bobbycar.camelk.kafka.topicZoneChange: {{ .Values.mqtt2kafka.kafka.topicZoneChange }}
    com.redhat.bobbycar.camelk.mqtt.brokerUrl: {{ .Values.mqtt2kafka.mqtt.host }}
    com.redhat.bobbycar.camelk.mqtt.topic: {{ .Values.mqtt2kafka.mqtt.topic }}
    com.redhat.bobbycar.camelk.mqtt.topicZoneChange: {{ .Values.mqtt2kafka.mqtt.topicZoneChange }}
type: Opaque

    
