kind: Secret
apiVersion: v1
metadata:
  name: mqtt2kafka-secret
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.kafka.brokers: bobbycar-cluster-kafka-brokers:9092
    com.redhat.bobbycar.camelk.kafka.topic: {{ .Values.kafka.topic.metrics }}
    com.redhat.bobbycar.camelk.kafka.topicZoneChange: {{ .Values.kafka.topic.zonechange }}
    com.redhat.bobbycar.camelk.mqtt.brokerUrl: tcp://bobbycar-amq-mqtt-all-0-svc:61616
    com.redhat.bobbycar.camelk.mqtt.topic: {{ .Values.mqtt.topic.mqttMetricsTopic }}
    com.redhat.bobbycar.camelk.mqtt.topicZoneChange: {{ .Values.mqtt.topic.mqttZoneChangeTopic }}
type: Opaque

    
