apiVersion: v1
kind: ConfigMap
metadata:
  name: rover-kafka2s3-config
  namespace: $(NS_ROVER)
data:
  application.properties: |
    
    kafka.broker.uri=rover-cluster-kafka-bootstrap:9092
    kafka.broker.topic.gps=rover-gps

    s3.accessKey=replacme
    s3.secretKey=replaceme
    s3.region=eu-central-1
    s3.bucket.name=rover-ml
    s3.message.aggregation.interval=10000
    s3.custom.endpoint.enabled=false
    s3.custom.endpoint.url=s3-openshift-storage.$(OCP_DOMAIN)

    