apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- operator-group.yaml
- 3scale-registry-secret.yaml
- 3scale-operator-subscription.yaml
- 3scale-apimanager.yaml
# - 3scale-kafka-http-api.yaml

