apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: bobbycar-amq-mqtt
  namespace: {{ .Values.namespace }}
spec:
  deploymentPlan:
    size: {{ .Values.amqBroker.instances }}
    image: registry.redhat.io/amq7/amq-broker:7.8
    requireLogin: false
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
  console:
    expose: {{ .Values.amqBroker.console.expose }}
  acceptors:
    - name: all
      port: 61616
      expose: true