{{- if .Values.components.enabled.kafka -}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.strimziOperator.name }}
  namespace: {{ .Values.namespace }}
spec:
  channel: stable
  installPlanApproval: {{ .Values.strimziOperator.installPlanApproval }}
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.strimziOperator.startingCSV }}
  {{- end }}  