{{- if .Values.components.enabled.kafka -}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-60"
spec:
  channel: {{ .Values.strimziOperator.channel }}
  installPlanApproval: {{ .Values.strimziOperator.installPlanApproval }}
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.strimziOperator.startingCSV }}
  {{- end }}  