{{- if .Values.components.enabled.datagrid -}}
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: bobbycar-dg
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.datagrid.replicas }}
  service:
    type: {{ .Values.datagrid.type }}
    container:
      storage: 2Gi
  container:
    cpu: {{ .Values.datagrid.cpu }}
    extraJvmOpts: '-XX:NativeMemoryTracking=summary'
    memory: {{ .Values.datagrid.memory }}
  expose:
    type: Route
  logging:
    categories: 
      org.infinispan: info
      org.jgroups: info
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: fatal
{{- end }}    