{{- if .Values.components.enabled.datagrid -}}
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {{ .Values.datagrid.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.datagrid.replicas }}
  service:
    type: DataGrid
    container:
      storage: 2Gi
  container:
    cpu: '500m'
    extraJvmOpts: '-XX:NativeMemoryTracking=summary'
    memory: 1Gi
  expose: {}
  logging:
    categories: 
      org.infinispan: info
      org.jgroups: info
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: fatal
{{- end }}    