kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: datagrid
  namespace: {{ .Values.namespace }}
  labels:
    clusterName: bobbycar-dg
    infinispan_cr: bobbycar-dg
spec:
  host: bobbycar-dg-{{ .Values.namespace }}.{{ .Values.ocpDomain }}
  to:
    kind: Service
    name: bobbycar-dg
    weight: 100
  port:
    targetPort: 11222
  wildcardPolicy: None