{{- if .Values.components.enabled.datagrid -}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-80"
spec:
  channel: {{ .Values.datagridOperator.channel }}
  installPlanApproval: {{ .Values.datagridOperator.installPlanApproval }}
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.datagridOperator.startingCSV }}
{{- end }}  