apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: rover
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.kafka.bridge.replicas }}
  bootstrapServers: rover-cluster-kafka-bootstrap:9092
  http:
    port: {{ .Values.kafka.bridge.port }}
