{{- if .Values.components.enabled.kafka -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-bridge
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.kafka.bridge.name }}-{{ .Values.namespace }}.{{ .Values.ocpDomain }}
  to:
    kind: Service
    name: {{ .Values.kafka.bridge.name }}-bridge-service
    weight: 100
  port:
    targetPort: rest-api
  wildcardPolicy: None
{{- end }}   
