{{- if .Values.components.enabled.kafka -}}
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: bobbycar
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.kafka.bridge.replicas }}
  bootstrapServers: bobbycar-cluster-kafka-bootstrap:9092
  http:
    port: {{ .Values.kafka.bridge.port }}
{{- end }}  

