kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
data:
  settings.xml: >-
    <?xml version="1.0" encoding="UTF-8"?> <settings
    xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

      <servers>
        <server>
          <id>repo-release</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
        <server>
          <id>repo-snapshot</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <mirrors>
        <mirror>
          <id>mirror.default</id>
          <url>http://nexus3-bobbycar-dev.apps.ocp4.rhlab.de/repository/maven-public/</url>
          <mirrorOf>central</mirrorOf>
        </mirror>
      </mirrors>
      <profiles>
        <profile>
          <id>nexus</id>
        </profile>
      </profiles>
      <activeProfiles>
        <activeProfile>nexus</activeProfile>
      </activeProfiles>
    </settings>
