apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: car-sim-trigger
spec:
  bindings:
    - kind: TriggerBinding
      ref: car-sim-binding
  template:
    name: car-sim-template
