apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bobbycar-zone-audit
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bobbycar-zone-approval
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display