apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zone-change-faas
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: quay.io/bobbycar/zone-change-service