apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - car-simulator-route.yaml
  - car-simulator-service-monitor.yaml
  - car-simulator-svc.yaml
  - car-simulator-cm.yaml
  - car-simulator-dc.yaml