kind: Secret
apiVersion: v1
metadata:
  name: kafka-streaming
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.kafka.brokers: my-cluster-kafka-bootstrap:9092
    com.redhat.bobbycar.camelk.kafka.topic.gps: bobbycar-gps
    com.redhat.bobbycar.camelk.kafka.topic.metrics: bobbycar-metrics
    com.redhat.bobbycar.camelk.kafka.topic.zonechange: bobbycar-zonechange
type: Opaque

    
