kind: Secret
apiVersion: v1
metadata:
  name: kafka-streaming
stringData:
  application.properties: |-
    com.redhat.rover.camelk.kafka.brokers: my-cluster-kafka-bootstrap:9092
    com.redhat.rover.camelk.kafka.topic.gps: rover-gps
    com.redhat.rover.camelk.kafka.topic.metrics: rover-metrics
    com.redhat.rover.camelk.kafka.topic.zonechange: rover-zonechange
type: Opaque

    
