kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-streaming-service
  namespace: bobbycar
  labels:
    camel.apache.org/integration: kafka-streaming-service
spec:
  host: kafka-streaming-service-bobbycar.apps.ocp3.stormshift.coe.muc.redhat.com
  to:
    kind: Service
    name: kafka-streaming-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None