apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- camel-k-operator-subscription.yaml
- kafka-streaming-integration.yaml
- kafka-streaming-route.yaml
- kafka-streaming-svc.yaml




