apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bobbycar

resources:
- camel-k-operator-subscription.yaml
- camel-k-integration-platform.yaml
- kafka-streaming-integration.yaml
- kafka-streaming-route.yaml
- kafka-streaming-svc.yaml




