apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: rover-amq-mqtt
  namespace: $(NS_ROVER)
spec:
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.7
    requireLogin: false
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
  console:
    expose: true
  acceptors:
    - name: all
      port: 61616
      expose: true