apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bobbycar-machine-learning

resources:
- namespace.yaml
- operator-group.yaml
- amq-streams-operator-subscription.yaml
- kafka-cr.yaml

