apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.amqOperator.channel }}
  installPlanApproval: {{ .Values.amqOperator.installPlanApproval }}
  name: amq-broker
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.amqOperator.startingCSV }}
