{{- if .Values.installCamelK }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.camelKOperator.channel }}
  installPlanApproval: {{ .Values.camelKOperator.installPlanApproval }}
  name: red-hat-camel-k
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.camelKOperator.startingCSV }}
{{- end }}