{{- if .Values.installDatagrid }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.datagridOperator.channel }}
  installPlanApproval: {{ .Values.datagridOperator.installPlanApproval }}
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.datagridOperator.startingCSV }}
{{- end }}