apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: bobbycar-dg
spec:
  container:
    cpu: ''
    extraJvmOpts: ''
    memory: ''
  expose: {}
  image: ''
  logging:
    categories: 
      org.infinispan: info
  replicas: 1
  security:
    endpointEncryption:
      certSecretName: bobbycar-dg-certs-secret
      certServiceName: service.beta.openshift.io
      type: service
  endpointSecretName: bobbycar-dg-generated-secret
  service:
    container:
      storage: ''
    sites:
      local:
        expose: {}
        name: ''
      locations: null
    type: Cache