apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: bobbycar-dg
spec:
  container:
    cpu: 200m
    extraJvmOpts: '-XX:NativeMemoryTracking=summary -Dinfinispan.bind.address=0.0.0.0'
    memory: 1Gi
  expose:
    type: Route
  logging:
    categories:
      org.infinispan: info
      org.jgroups: info
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error
  replicas: 1
  security:
    authorization:
      enabled: false
    endpointAuthentication: false
  service:
    container:
      storage: 1Gi
    type: DataGrid
