kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8778/TCP
  - 8080/TCP
  - 8443/TCP
  Application: app
  Project: amq-tls
  Name: device-registry
  Url:
  - Name: device-registry-8080
    Port: 8080
