apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- amq-broker/
- amq-streams/
#- amq-streams-mirror/
- api-gateway/
- camel-k/
- datagrid/
- car-simulator/manifests/
- dashboard/manifests/
- datagrid-rest-service/manifests/
- kafka-streaming-service/manifests/
- kafka2datagrid-service/manifests/
- kafka2s3-service/manifests/
#- keycloak

resources:
- namespace.yaml
- operator-group.yaml



