apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- amq-broker/
- amq-streams/
- api-gateway/
- car-simulator/manifests/
- dashboard/manifests/
- kafka-streaming-service/manifests/

resources:
- namespace.yaml
- operator-group.yaml



