kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: carsim-pipe-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pipeline.rover.storage }}
  volumeMode: Filesystem
