kind: Secret
apiVersion: v1
metadata:
  name: kafka2datagrid-secret
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.dg.car.snapshot.cacheName: carsnapshots
    com.redhat.bobbycar.camelk.dg.car.cacheName: cars
    com.redhat.bobbycar.camelk.dg.zone.cacheName: zones
    com.redhat.bobbycar.camelk.dg.host: bobbycar-dg.camelk-test.svc.cluster.local
    com.redhat.bobbycar.camelk.dg.password: CGFFKAGLyIluavWA
    com.redhat.bobbycar.camelk.dg.user: operator
    com.redhat.bobbycar.camelk.kafka.brokers: my-cluster-kafka-brokers:9092
    com.redhat.bobbycar.camelk.kafka.topic: bobbycar-gps
    com.redhat.bobbycar.camelk.mqtt.brokerUrl: tcp://bobbycar-amq-mqtt-all-0-svc:61616
    com.redhat.bobbycar.camelk.mqtt.topic: bobbycar/zonechange
    com.redhat.bobbycar.camelk.dg.ocp.api: api.ocp4.rhlab.de
    com.redhat.bobbycar.camelk.dg.namespace: camelk-test
type: Opaque

    
