apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bobbycar

resources:
- kafka2datagrid-integration.yaml
- kafka2datagrid-secret.yaml
- sa-rolebinding.yaml
- view-zones-role.yaml



