apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-zones
  namespace: rover
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - rover.redhat.com
    resources:
      - '*'