namespace:
appName: Rover
ocpDomain:
ocpApi:

mqtt:
  topic:
    mqttZoneChangeTopic: rover/zonechange
    mqttMetricsTopic: rover/enginemetrics

kafka:
  topic:
    gps: rover-gps
    metrics: rover-metrics
    zonechange: rover-zonechange
  bootstrap:
    servers: rover-cluster-kafka-bootstrap:9092

datagrid:
  cache:
    snapshot: carsnapshots
    car: cars
    zone: zones
    refresh:
      interval: 10000
  account:
    user: replaceme
    password: replaceme

dashboard:
  config:
    googleApiKey:
    threeScaleApiKey: replaceme
    hdppEndpoint: http://ntt-stream-hdpp.apps.ocp4.rhlab.de/playlist.m3u8

carSimulator:
  name: car-simulator 
  replicas: 1
  config:
    carsimCars: 20
    carsimFactor: 3
    carsimRepeat: true
    carsimDelay: 1000
imageCredentials:
  name: priv-registry-key
  registry: quay.io
  username: replaceme
  password: replaceme
  email: replaceme
