kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: datagrid-to-rest
  labels:
    camel.apache.org/integration: datagrid-to-rest-route
spec:
  to:
    kind: Service
    name: datagrid-to-rest
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None