
namespace:
appName: Bobbycar
ocpDomain:
ocpApi:

mqtt:
  topic:
    mqttZoneChangeTopic: bobbycar/zonechange
    mqttMetricsTopic: bobbycar/enginemetrics

kafka:
  topic:
    gps: bobbycar-gps
    metrics: bobbycar-metrics
    zonechange: bobbycar-zonechange

datagrid:
  cache:
    snapshot: carsnapshots
    car: cars
    zone: zones
  account:
    user: operator
    password:

dashboard:
  config:
    googleApiKey:
    threeScaleApiKey: replaceme

carSimulator:
  name: car-simulator 
  replicas: 1
  config:
    carsimCars: 20
    carsimFactor: 3
    carsimRepeat: true
    carsimDelay: 1000