apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: bobbycar

resources:
- ../components

patchesStrategicMerge:
- patches/kafka-bridge.yaml
- patches/3scale-registry-secret.yaml
- patches/datagrid-route.yaml
- patches/dashboard-configmap.yaml
- patches/dashboard-route.yaml
- patches/kafka2s3-cm.yaml

configMapGenerator:
  - name: bobbycar-deployment-config
    namespace: bobbycar
    literals:
    - OCP_DOMAIN=apps.ocp4.stormshift.coe.muc.redhat.com
    - NS_BOBBYCAR=bobbycar
    - NS_BOBBYCAR_API=bobbycar-api
    - NS_BOBBYCAR_ML=bobbycar-machine-learning
  
vars:
- name: OCP_DOMAIN
  objref:
    kind: ConfigMap
    name: bobbycar-deployment-config
    apiVersion: v1
  fieldref:
    fieldpath: data.OCP_DOMAIN 
- name: NS_BOBBYCAR
  objref:
    kind: ConfigMap
    name: bobbycar-deployment-config
    apiVersion: v1
  fieldref:
    fieldpath: data.NS_BOBBYCAR
- name: NS_BOBBYCAR_API
  objref:
    kind: ConfigMap
    name: bobbycar-deployment-config
    apiVersion: v1
  fieldref:
    fieldpath: data.NS_BOBBYCAR_API
- name: NS_BOBBYCAR_ML
  objref:
    kind: ConfigMap
    name: bobbycar-deployment-config
    apiVersion: v1
  fieldref:
    fieldpath: data.NS_BOBBYCAR_ML              
    
generatorOptions:
  disableNameSuffixHash: true  

configurations:
- varreference.yaml