apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: rover
  namespace: $(NS_ROVER)
spec:
  replicas: 2
  bootstrapServers: rover-cluster-kafka-bootstrap:9092
  http:
    port: 8080
 

