apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: rover-gps
  namespace: $(NS_ROVER)
  labels:
    strimzi.io/cluster: rover-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 
