apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: bobbycar-gps
  namespace: bobbycar
  labels:
    strimzi.io/cluster: bobbycar-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 
