kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-bridge
  namespace: $(NS_ROVER)
spec:
  to:
    kind: Service
    name: rover-bridge-service
    weight: 100
  port:
    targetPort: rest-api
  wildcardPolicy: None
