apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  namespace: $(NS_BOBBYCAR)
spec:
  channel: techpreview
  installPlanApproval: Automatic
  name: red-hat-camel-k
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: red-hat-camel-k-operator.v1.0.0