apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: zoneChange
spec:
  filter:
    attributes:
      type: zoneChange
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: zone-change