kind: Secret
apiVersion: v1
metadata:
  name: mqtt2kafka
stringData:
  application.properties: |-
    com.redhat.rover.camelk.kafka.brokers: {{ .Values.kafka.bootstrap.servers }}
    com.redhat.rover.camelk.kafka.topic: {{ .Values.kafka.topic.metrics }}
    com.redhat.rover.camelk.kafka.topicZoneChange: {{ .Values.kafka.topic.zonechange }}
    com.redhat.rover.camelk.mqtt.brokerUrl: tcp://rover-amq-mqtt-all-0-svc:61616
    com.redhat.rover.camelk.mqtt.topic: {{ .Values.mqtt.topic.mqttMetricsTopic }}
    com.redhat.rover.camelk.mqtt.topicZoneChange: {{ .Values.mqtt.topic.mqttZoneChangeTopic }}
type: Opaque

    
