# Default values for bobbycar-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: bc
appName: Bobbycar
ocpDomain: apps.ocp4.stormshift.coe.muc.redhat.com

# Enable the components that should be installed
components:
  enabled:
    camelK: true
    kafka: true
    datagrid: true
    amqBroker: true

# AMQ Broker Operator Subscription
amqOperator:
  installPlanApproval: Automatic
  startingCSV: amq-broker-operator.v0.18.0
  channel: current

# Camel-K Operator Subscription
camelKOperator:
  installPlanApproval: Automatic
  startingCSV: red-hat-camel-k-operator.v1.0.0
  channel: techpreview

# Datagrid Operator Subscription
datagridOperator:
  installPlanApproval: Automatic
  startingCSV: datagrid-operator.v8.0.3
  channel: 8.0.x

# AMQ Streams Operator Subscription
strimziOperator:
  installPlanApproval: Automatic
  startingCSV: amqstreams.v1.6.1
  channel: stable

datagrid:
  replicas: 1
  type: DataGrid
  cpu: '500m'
  memory: 1Gi

amqBroker:
  instances: 1
  console:
    expose: true  

kafka: 
  cluster:
    brokerReplicas: 2
    zookeeperReplicas: 3
  bridge: 
    replicas: 1
    port: 8080
  topic:
    gps:
      name: bobbycar-gps
      partitions: 1
      replicas: 1
      retention: 60000
    metrics:
      name: bobbycar-metrics
      partitions: 1
      replicas: 1
      retention: 60000
    zonechange:
      name: bobbycar-zonechange
      partitions: 1
      replicas: 1
      retention: 300000